name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Xamarin
      # You may pin to the exact commit or the version.
      # uses: maxim-lobanov/setup-xamarin@00b44a3ef9e2d1953010956de2022e8d095a196c
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        # Version of Mono to select
        mono-version: latest # optional
        # Version of Xamarin.iOS to select
        xamarin-ios-version: latest # optional
        # Version of Xamarin.Mac to select
        xamarin-mac-version: latest # optional
        # Version of Xamarin.Android to select
        xamarin-android-version: latest # optional
        # Version of Xcode to use with Xamarin.iOS and Xamarin.Mac
        xcode-version: latest # optional
    - name: Restore dependencies
      run: dotnet restore ./reef.project/reef.testing/
    - name: Build
      run: msbuild ./reef.project/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./reef.project/reef.testing/
